spring:
  application:
    name: store
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: admin1234
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 8000
    refreshTokenExpiration: 604800

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  wehbookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
websiteUrl: http://localhost:3000